name: harry_potter_adilet
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  auto_route: ^9.1.0
  easy_sidemenu: ^0.7.1
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  dio: ^5.9.0
  get_it: ^8.0.0
  json_annotation: ^4.9.0
  dartz: ^0.10.1
  equatable: ^2.0.7
  lottie: ^3.1.3
  flutter_tts: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.9
  flutter_gen_runner: 5.4.0
  auto_route_generator: ^9.0.0
  json_serializable: ^6.8.0

  # Linting
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets: 
    - assets/images/
    - assets/lottie/
  
  fonts:
    - family: HarryPotter
      fonts:
        - asset: fonts/HarryPotter.ttf
          weight: 500

